/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule AddTripMutation.graphql
 * @generated SignedSource<<400d464b272fe8fc2079d9c61276e18e>>
 * @relayHash 8d8150fc1472ce15db5cc00506ae8280
 * @flow
 * @nogrep
 */

/* eslint-disable */

'use strict';

/*::
import type {ConcreteBatch} from 'relay-runtime';
export type TripInputType = {
  created_by?: ?string;
  destination_name?: ?string;
  travel_time?: ?number;
};

export type AddTripMutationResponse = {
  id?: ?string;
};
*/


/*
mutation AddTripMutation(
  $trip: TripInputType!
) {
  addTrip(trip: $trip) {
    id
  }
}
*/

const batch /*: ConcreteBatch*/ = {
  "fragment": {
    "argumentDefinitions": [
      {
        "kind": "LocalArgument",
        "name": "trip",
        "type": "TripInputType!",
        "defaultValue": null
      }
    ],
    "kind": "Fragment",
    "metadata": null,
    "name": "AddTripMutation",
    "selections": [
      {
        "kind": "LinkedField",
        "alias": null,
        "args": [
          {
            "kind": "Variable",
            "name": "trip",
            "variableName": "trip",
            "type": "TripInputType!"
          }
        ],
        "concreteType": "Trip",
        "name": "addTrip",
        "plural": false,
        "selections": [
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "id",
            "storageKey": null
          }
        ],
        "storageKey": null
      }
    ],
    "type": "Mutation"
  },
  "id": null,
  "kind": "Batch",
  "metadata": {},
  "name": "AddTripMutation",
  "query": {
    "argumentDefinitions": [
      {
        "kind": "LocalArgument",
        "name": "trip",
        "type": "TripInputType!",
        "defaultValue": null
      }
    ],
    "kind": "Root",
    "name": "AddTripMutation",
    "operation": "mutation",
    "selections": [
      {
        "kind": "LinkedField",
        "alias": null,
        "args": [
          {
            "kind": "Variable",
            "name": "trip",
            "variableName": "trip",
            "type": "TripInputType!"
          }
        ],
        "concreteType": "Trip",
        "name": "addTrip",
        "plural": false,
        "selections": [
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "id",
            "storageKey": null
          }
        ],
        "storageKey": null
      }
    ]
  },
  "text": "mutation AddTripMutation(\n  $trip: TripInputType!\n) {\n  addTrip(trip: $trip) {\n    id\n  }\n}\n"
};

module.exports = batch;
