/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule AddTripMutation.graphql
 * @generated SignedSource<<be8fd3a1f64b80b55e5c097e9e210e61>>
 * @relayHash 7a198f93a37bbd7e7be95eeb44a2877e
 * @flow
 * @nogrep
 */

/* eslint-disable */

'use strict';

/*::
import type {ConcreteBatch} from 'relay-runtime';
export type AddTripInputType = {
  created_by?: ?string;
  from?: ?string;
  to?: ?string;
  travel_time?: ?number;
};

export type AddTripMutationResponse = {
  id?: ?string;
};
*/


/*
mutation AddTripMutation(
  $input: AddTripInputType!
) {
  addTrip(input: $input) {
    id
  }
}
*/

const batch /*: ConcreteBatch*/ = {
  "fragment": {
    "argumentDefinitions": [
      {
        "kind": "LocalArgument",
        "name": "input",
        "type": "AddTripInputType!",
        "defaultValue": null
      }
    ],
    "kind": "Fragment",
    "metadata": null,
    "name": "AddTripMutation",
    "selections": [
      {
        "kind": "LinkedField",
        "alias": null,
        "args": [
          {
            "kind": "Variable",
            "name": "input",
            "variableName": "input",
            "type": "AddTripInputType!"
          }
        ],
        "concreteType": "Trip",
        "name": "addTrip",
        "plural": false,
        "selections": [
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "id",
            "storageKey": null
          }
        ],
        "storageKey": null
      }
    ],
    "type": "Mutation"
  },
  "id": null,
  "kind": "Batch",
  "metadata": {},
  "name": "AddTripMutation",
  "query": {
    "argumentDefinitions": [
      {
        "kind": "LocalArgument",
        "name": "input",
        "type": "AddTripInputType!",
        "defaultValue": null
      }
    ],
    "kind": "Root",
    "name": "AddTripMutation",
    "operation": "mutation",
    "selections": [
      {
        "kind": "LinkedField",
        "alias": null,
        "args": [
          {
            "kind": "Variable",
            "name": "input",
            "variableName": "input",
            "type": "AddTripInputType!"
          }
        ],
        "concreteType": "Trip",
        "name": "addTrip",
        "plural": false,
        "selections": [
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "id",
            "storageKey": null
          }
        ],
        "storageKey": null
      }
    ]
  },
  "text": "mutation AddTripMutation(\n  $input: AddTripInputType!\n) {\n  addTrip(input: $input) {\n    id\n  }\n}\n"
};

module.exports = batch;
