/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule HomeMutation.graphql
 * @generated SignedSource<<4264e899eed662870ca8953571e03710>>
 * @relayHash eb414172b998640ff35499e4ff186bfe
 * @flow
 * @nogrep
 */

/* eslint-disable */

'use strict';

/*::
import type {ConcreteBatch} from 'relay-runtime';
export type RemoveTripInputType = {
  id?: ?string;
};

export type HomeMutationResponse = {
  id?: ?string;
};
*/


/*
mutation HomeMutation(
  $input: RemoveTripInputType!
) {
  removeTrip(input: $input) {
    id
  }
}
*/

const batch /*: ConcreteBatch*/ = {
  "fragment": {
    "argumentDefinitions": [
      {
        "kind": "LocalArgument",
        "name": "input",
        "type": "RemoveTripInputType!",
        "defaultValue": null
      }
    ],
    "kind": "Fragment",
    "metadata": null,
    "name": "HomeMutation",
    "selections": [
      {
        "kind": "LinkedField",
        "alias": null,
        "args": [
          {
            "kind": "Variable",
            "name": "input",
            "variableName": "input",
            "type": "RemoveTripInputType!"
          }
        ],
        "concreteType": "Trip",
        "name": "removeTrip",
        "plural": false,
        "selections": [
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "id",
            "storageKey": null
          }
        ],
        "storageKey": null
      }
    ],
    "type": "Mutation"
  },
  "id": null,
  "kind": "Batch",
  "metadata": {},
  "name": "HomeMutation",
  "query": {
    "argumentDefinitions": [
      {
        "kind": "LocalArgument",
        "name": "input",
        "type": "RemoveTripInputType!",
        "defaultValue": null
      }
    ],
    "kind": "Root",
    "name": "HomeMutation",
    "operation": "mutation",
    "selections": [
      {
        "kind": "LinkedField",
        "alias": null,
        "args": [
          {
            "kind": "Variable",
            "name": "input",
            "variableName": "input",
            "type": "RemoveTripInputType!"
          }
        ],
        "concreteType": "Trip",
        "name": "removeTrip",
        "plural": false,
        "selections": [
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "id",
            "storageKey": null
          }
        ],
        "storageKey": null
      }
    ]
  },
  "text": "mutation HomeMutation(\n  $input: RemoveTripInputType!\n) {\n  removeTrip(input: $input) {\n    id\n  }\n}\n"
};

module.exports = batch;
